version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=facemate_password
      - DB_NAME=face_recognizer
      - FLASK_ENV=production
    depends_on:
      - db
    volumes:
      - ./face_encodings.pkl:/app/face_encodings.pkl
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=facemate_password
      - MYSQL_DATABASE=face_recognizer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
